### ISSUE TITLE
Add creator_type to template

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#10]
This template is missing `creator_type` attribute.

https://github.com/ioos/ioos-atn-data/blob/master/templates/atn_trajectory_template.cdl

**Comment by MathewBiddle** [comment]
possibly include `creator_address`, `creator_city`, `creator_country`, `creator_phone`, `creator_sector`

**Comment by iamchrisser** [comment]
We ask for but don't require the address, city, country, and phone fields. We don't collect `PI sector` yet, which is how we'd get `creator_sector`. Can we move forward without this for now, or hard code one of the values from https://mmisw.org/ont/ioos/sector for now? None of those values seem universally appropriate though, aside from `unknown` or `other`, neither of which add to the metadata.

**Comment by MathewBiddle** [comment]
We can put the attributes in the files, just don't populate them until you start collecting the information.

**Comment by mmckinzie** [comment]
if we are going to include the creator_address, city, country and phone, we should also included creator_city and creator_postalcode

**Comment by iamchrisser** [comment]
All these creator fields are included in the new example file. We ask for all of these in the reg app, except for `creator_sector`.

**Comment by MathewBiddle** [comment]
Looks good:
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L329-L332
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L322-L323
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L312-L313
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L302-L303
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L258
