### ISSUE TITLE
These attribute's aren't in the most recent example

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#11]
The example, https://github.com/ioos/ioos-atn-data/blob/master/templates/atn_trajectory_template_ncdump.txt doesn't have these attributes. Is there a reason for this?

https://github.com/ioos/ioos-atn-data/blob/d603e284a164f2f6a2f9856719cdd10ad631bf34/templates/atn_trajectory_template.cdl#L255-L258

**Comment by mmckinzie** [comment]
first_uplink_date and last_uplink_date  are OK to remove from template. 
last_location_lat, last_location_lon and last_location_date need to be included

**Comment by iamchrisser** [comment]
None of those attributes are in our template spec. I'll add them.

**Comment by iamchrisser** [comment]
Sorry, these are in the initial netCDFs we generate, but we were removing them because they aren't in [the spreadsheet](https://docs.google.com/spreadsheets/d/1nYjpo5rF3W2qPV_XKva63g7VUv3Q659Z48ri9qXnF0g/edit#gid=1371204623) where we started defining these templates. I've changed our notebook so they'll not be removed and have added them to the spreadsheet.

**Comment by mmckinzie** [comment]
@iamchrisser yes we do need first_location_lat, first_location_long and first_location_date.

**Comment by MathewBiddle** [comment]
@mmckinzie sounds like we don't need this.

**Comment by iamchrisser** [comment]
The recent commit includes first_location_lat, first_location_lon, first_location_date, last_location_lat, last_location_lon, and last_location_date.

**Comment by mmckinzie** [comment]
@iamchrisser @MathewBiddle I was confusing these attributes with something else when I commented awhile back suggesting we keep. Please go ahead and remove first_location_lat, first_location_lon, first_location_date, last_location_lat, last_location_lon, and last_location_date. Reported values were being generated from the data files themselves and are duplicates of what is reported within time_coverage_end and time_coverage_start.

Alternatively, we do need to add:  deployment_start_lat, deployment_start_lon, deployment_start_datetime and deployment_end_datetime. 

That information is provided by researcher in the Reg App and reports actual deployment start and end date/times and deployment location so data can be appropriated truncated to the actual deployment window (biologically relevant data only) by future user of these data, e.g., remove pre-deployment testing positions on land or by manufacturer.

**Comment by iamchrisser** [comment]
OK. Do we also want `deplotment_end_lat`, `deplotment_end_lon` as optional fields?

**Comment by iamchrisser** [comment]
Thinking about this now, it doesn't seem appropriate to ask for these in the reg app. I think that many deplyoment ends are determined when the tag stops transmitting, but that's not 100% the case so we can't just add the last location values in the data as the values for these attributes. My preference would be to not include these attributes. It that sonds OK to you @MathewBiddle  and @mmckinzie , please close this issue.

**Comment by mmckinzie** [comment]
@iamchrisser @MathewBiddle I agree we don't need deployment_end_lat or deployment_end_lon

But we do need to add: deployment_start_lat, deployment_start_lon, deployment_start_datetime and deployment_end_datetime

These values are already provided by researchers in the Reg App. It reports actual deployment start and end date/times and deployment location so data can be appropriately truncated to the actual deployment window (biologically relevant data only) by future user of these data, e.g., remove pre-deployment testing positions on land or generated by manufacturer, or post-deployment locations generated after tag, for example, has molted off animal. These values are not generated from the data themselves but critical to future reuse of these data.

**Comment by MathewBiddle** [comment]
+1 @mmckinzie. Let's be sure we use ISO8601 for date and decimal degrees east/north for lon/lats. 

Something for V2 - maybe this should be a flag `ancillary_variable` that gets added to the coordinate variables? Sticking this information into an attribute obfuscates its usefulness to an unknown users. A flag would at least tell the user that there is an `ancillary_variable` which documents the validity of the coordinates (time and space). Should be easy to code up if the Reg App records the information in standard formats.

**Comment by mmckinzie** [comment]
@MathewBiddle all dates are already reported in (converted to) ISO8601 and lat/lon in decimal degrees once metadata are entered into the Reg App regardless of the formats provided by researcher or reported within original csv upload. 

Lets discuss the anillary_variables as an option for V2. That seems like a logical suggestion.
