### ISSUE TITLE
All dates should be ISO 8601

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#12]
See this, for example:
https://github.com/ioos/ioos-atn-data/blob/d603e284a164f2f6a2f9856719cdd10ad631bf34/templates/atn_trajectory_template_ncdump.txt#L241

**Comment by iamchrisser** [comment]
This should be fixed in the next update I send along.

**Comment by MathewBiddle** [comment]
looks like `last_uplink_date` didn't get fixed:
https://github.com/ioos/ioos-atn-data/blob/3c36a14f87c54c6ba154c822514a9072fb38181f/data/examples/atn_trajectory_template_ncdump.txt#L240

But, that depends on #11

**Comment by iamchrisser** [comment]
Sorry, I should have dropped that attribute.

**Comment by iamchrisser** [comment]
Fixed in the recent commit.

**Comment by MathewBiddle** [comment]
fixed in https://github.com/ioos/ioos-atn-data/commit/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4
