### ISSUE TITLE
Global attribute tag_id vs ptt

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#13]
See https://github.com/ioos/ioos-atn-data/blob/d603e284a164f2f6a2f9856719cdd10ad631bf34/templates/atn_trajectory_template.cdl#L269 vs https://github.com/ioos/ioos-atn-data/blob/d603e284a164f2f6a2f9856719cdd10ad631bf34/templates/atn_trajectory_template_ncdump.txt#L255

Which one do we prefer?

**Comment by mmckinzie** [comment]
the satellite tag community generally uses ptt, but I think using tag_id may make template more flexible for non-Argos transmitting devices.

**Comment by MathewBiddle** [comment]
Agreed.

**Comment by iamchrisser** [comment]
Same. We switched to `tag_id` at Megan's request, but could switch back if needed.

**Comment by MathewBiddle** [comment]
Looks good!

https://github.com/ioos/ioos-atn-data/blob/3c36a14f87c54c6ba154c822514a9072fb38181f/data/examples/atn_trajectory_template_ncdump.txt#L256

**Comment by MathewBiddle** [comment]
switch back to `ptt`

**Comment by iamchrisser** [comment]
This is reverted back to ptt in the recent commit.

**Comment by MathewBiddle** [comment]
fixed with https://github.com/ioos/ioos-atn-data/commit/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4

**Comment by iamchrisser** [comment]
@mmckinzie @MathewBiddle 
We talked about this on our most recent call, and I think that we agreed that we'd include both `ptt` and `tag_id` attributes. We have a few options for how we might do that. 

1. When files contain just satellite data, these two attributes will contain the same values. 
2. When the data file contains no satellite data (like some dtag deployments), only the `tag_id` attribute will contain an ID value.
3. When the file contains data from both a satellite tag and another type of tag (dtag), the `ptt` attribute will have the ID of the satellite tag and the `tag_id` attribute will hold the identifier for the other tag.

A few follow up questions:

- W.r.t. #2 above, when there's not satellite location data, do we want the file to have an empty `ptt` attribute, leave the attribute out? If we do include the `ptt` attribute, do we want to use something like "NA" when the field would be empty?
- Re #3, do we expect that we might have more than 2 tags on an animal? If yes, we'll need to rethink this approach.

**Comment by MathewBiddle** [comment]
This proposal looks good to me, thanks @iamchrisser for laying it out.

> W.r.t. 2 above, when there's not satellite location data, do we want the file to have an empty ptt attribute, leave the attribute out? If we do include the ptt attribute, do we want to use something like "NA" when the field would be empty?

Definitely keep the attribute there.  Leaving it blank could lead to confusion (was it intentionally blank? Was there a mistake in the file generation? etc.). My recommendation: Keep the attribute and instead of `NA`, put something more descriptive like `Not available`.

> Re 3, do we expect that we might have more than 2 tags on an animal? If yes, we'll need to rethink this approach.

Thinking back to how we are defining a file, isn't it based on the tag deployment? So, if there were two tags there would be two files? 

If that's true, we might need to think about how we would link the two files together...If that's something to consider it should be a new ticket.

**Comment by iamchrisser** [comment]
What do you think about `Not applicable` instead of `Not available`? The latter seems like it could be interpreted to mean something like we just couldn't find or access that info, but that it exists. 

As for keeping data from different tags in different files, I like that approach, too. It's conceptually clearer that one or more tags can be deployed on an animal, rather than an animal being deployed with one or more tags.  On the last  call though, I thought we learned that the NCEI preference was to have each/all of the tags archived in a single file. It seems much easier  and cleaner not to mix deployments across files. Let's clarify this tomorrow.

**Comment by mmckinzie** [comment]
wrt 1 above....generally if a satellite tag/deployment the tag_id and the PTT will be the same, but there are some cases where they will be different (e.g., PTT reused and assigned to a different device, which is applied on a new animal), This is a different use case then when the tag itself is reused (PTT and tag_id remain the same) but deployment on a different animal. Another reason to always report both. 

regarding 2 above...I agree we should keep the PTT attribute in cases where tag does not have an Argos transmitter (Dtag, GSM). I also like not applicable over not available or NA.

If two devices (Dtag + SPOT tag OR SPOT tag + PAT tag, etc...) are deployed on the same animal those data should be kept separate and archived as two distinct data files, so yes we need to determine best way to link files so it is clear those files were deployed on the same animal at the same time over same animal at different times, so simultaneously over sequentially. But in the Dtag example, there will be cases where the Argos transmitters are integrated into the same device, so the location data, LC, error radius, ect...should be reported along with the other suite of traditional Dtag sensor data (e.g., accelerometer, magnetometer, pressure, temp)  within the same, single data file. So one device, one file. If two devices, two files.

**Comment by mmckinzie** [comment]
@iamchrisser @MathewBiddle 

Can we update tag_id to instrument_id? and ptt to instrument_ptt_id?

This will better align with other national telemetry networks, MEOP and AniBOS  requirements/use of these attributes in their templates and with nc-eTAG specifications.

**Comment by iamchrisser** [comment]
fine with me. That's how it'll look in the next template.

**Comment by iamchrisser** [comment]
ping @mmckinzie

**Comment by mmckinzie** [comment]
@iamchrisser Yes we agreed to only have one data type per file. But no the values reported within the instrument_id and instrument_ptt_id should not be the same id. PTT is of course the assigned ptt id which is often used as an instrument identifier but it is not always a unique instrument identifier as ptt's can be reused and assigned to more than instrument over time.

Therefore, other networks often also include an instrument id, which is meant to be a unique identifier and has been reported by others as manufacturer:model:serialnumber or in some cases a unique user assigned id and others report the serial numbers as instrument ids.  

Considering we haven't agreed to what should be reported within an instrument_id field, if included and we may have to harvest metadata from the ADR to generate a unique id and that will take Dave time and we already report serial numbers within the instrument variables, lets just skip instrument_id for now and just keep the ptt_id.  Sorry for the confusion.

**Comment by iamchrisser** [comment]
Summarizing to make sure I understand:

- we're going to continue to use `ptt_id`, which is not globally unique but is unique within a project (I think)
- we'll record the `serial_number` for each instrument as a variable attribute on the appropriate variable
- we'll NOT use the `tag_id` field or the `instrument_id` fields

That all seems fine. I just need to drop the `tag_id` field from the template and we'll be done with this.
