### ISSUE TITLE
geospatial resolutions

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#15]
need to include geospatial resolution global attributes for lat, lon, and vertical.

**Comment by mmckinzie** [comment]
I will need to confirm with manufacturers regarding what values should be correctly reported within these attributes (e.g., 0.10).

**Comment by iamchrisser** [comment]
I don't remember why, but at some point earlier in this process we talked about how these attributes don't make sense for this data. According to the [definition in the NCEI template](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/), this attribute is supposed to provide
>  Information about the targeted spacing of points in latitude. Recommend describing resolution as a number value followed by the units. Does not apply to discrete sampling geometries (non-gridded data). Not to be confused with measurement resolution.
I think we don't know the resolution of the data in these deployment files. Doesn't that depend on how frequently an animal surfaces and pings the satellite?

**Comment by MathewBiddle** [comment]
I think were talking about two different things here. Resolution vs precision? In the definition @iamchrisser included it clearly states `Does not apply to discrete sampling geometries (non-gridded data).` So we might be okay not including it.

**Comment by mmckinzie** [comment]
That sounds reasonable to me. Seems like it would be OK to remove/skip.

**Comment by iamchrisser** [comment]
OK to close this issue then?

**Comment by MathewBiddle** [comment]
yup
