### ISSUE TITLE
add length, weight, and other animal attributes as variables?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#16]
We can add them as variables

```
animal_length()
   animal_length:unit = "m" ;

animal_weight()
   animal_weight:unit= "kg" ;

animal_sex()
   animal_sex:unit = "" ;
   animal_sex:vocabulary = "";

animal_stage()
   animal_stage: unit = "" ;
```

**Comment by albenson-usgs** [comment]
http://vocab.nerc.ac.uk/collection/P01/current/TL01XX01/

**Comment by mmckinzie** [comment]
Abby- I am probably just being dense, but is there a full list of accepted length types? Total length is just one example of what is sometimes reported, but often standard length, fork length, curved carapace length, are reported instead of total length. I guess what I am getting at is that the length_type attribute needs to be flexible.

**Comment by mmckinzie** [comment]
Also I think that animal_stage should be animal_life_stage and we would also need to add animal_age and animal_age_units.

e.g., animal_life_stage = juvenile
e.g., animal_age = 2
e.g., animal_age_units = years

**Comment by mmckinzie** [comment]
I also think all of these variable may need to get referenced with platform_ and not animal_, as the platform is the animal?

**Comment by albenson-usgs** [comment]
I think there was a comment that disappeared but I linked specifically to the total length term in NERC but there are other length types. There is also standard length (http://vocab.nerc.ac.uk/collection/P01/current/SL01XX01/) and fork length (http://vocab.nerc.ac.uk/collection/P01/current/FL01XX01/). I don't think carapace length is in NERC so someone would need to request it be added.

**Comment by MathewBiddle** [comment]
Okay, lots to think about here. What you can see below is how I've created new variables for that information:
https://github.com/ioos/ioos-atn-data/blob/f535f97e65dd65a5210d0cbd08c14482a72f9050/templates/atn_trajectory_template.cdl#L197-L206

In my opinion, the `animal_length_type` information should be an attribute of the `animal_length` variable as it's a descriptor of the observation. That would look something like:
```
double animal_length(animal_obs) ;
		animal_length:units = "m" ;
		animal_length:long_name = "length of the animal" ;
		animal_length:length_type = "total length" ;
		animal_length:length_type_vocabulary = "http://vocab.nerc.ac.uk/collection/P01/current/TL01XX01/" ;
```
We can fiddle with the names of the attributes to be more appropriate, like  `length_type_vocabulary` to `length_type_uri`? Or, maybe an attribute for `nerc_term` or `nerc_identifier`?


As for `animal_stage` -> `animal_life_stage`, sure. In the end, it doesn't matter all that much what you call the variables. As long as the attributes are appropriately documenting the variable.

That would look like:
```
string animal_life_stage(animal_obs) ;
		animal_life_stage:long_name = "stage of the animal (adult, juvenile)" ;
		animal_life_stage:nerc_identifier = "http://vocab.nerc.ac.uk/collection/S11/current/" ;
```
I added `nerc_identifier` to bring that connection to a controlled vocabulary which you will be using to populate the variable. We could use something like `source` as well, or even `animal_life_stage_vocabulary` if you want to be really verbose.


Also, notice I added a new dimension to the file `animal_obs`. This allows us to add multiple obs of the animal, if we have them. We can also create an `animal_obs_time(animal_obs)` variable which gives us a place to put the date/time of those observations. Or, we can add that as attributes to each of the above variables. Something to think about, but it should help w/ DwC conversion for @albenson-usgs

**Comment by MathewBiddle** [comment]
Also, these variables should have `platform` attributes, which point to the container variable for the platform (either `animal` or `platform`, whatever the name ends up being).  If we want to get pedantic, we should have instrument variables for each of these observations (length and weight, at least.). 

Let me know what changes to make and we can update the template.

**Comment by iamchrisser** [comment]
We identified these as nice to have for the ATN -> OBIS connection, but not something we had capacity to work on for the initial NCEI connection. I think that's spelled out in [the crosswalk](https://github.com/ioos/ioos-atn-data/blob/master/crosswalk/ATN_nc_to_DwC_OBIS_mapping.xlsx) - [here's the link](https://docs.google.com/spreadsheets/d/12pP4IY2oXFhkXvOePtizHnShhlmO0r7QOTxu5ETvNOA/edit#gid=0) to the google doc version which is a little easier to view on the web.

It's good to have this issue here though, as a reminder for when there's space in the workplan.

**Comment by mmckinzie** [comment]
I think there is a little confusion regarding importance of the length, weight, sex, life stage variables. These do need to be included in initial NCEI template and should be added to workplan and addressed, even before we get back to the DwC crosswalk.  This has been discussed in my coordinator and DAC calls with Axiom and It was also recently added to our YR 4 workplan and statement of work. Not all of these variables will be provided by PIs for each and every deployment, but this is essential information about the animal that needs to be associated with the other animal variables when data are archived at NCEI. Future users of the data will want/need this information if/when present. This information would be harvested from the Reg App. If I am missing something regarding why these can't be addressed now, happy to discuss.

**Comment by MathewBiddle** [comment]
After discussing with @mmckinzie why don't we do this as an interim solution. Add the information from the registration app as attributes to the platform variable. We can add them as free text strings for now, then look at using a controlled vocabulary in the future.

Something like:
```
platform:animal_length = "" ;
platform:animal_weight = "" ;
platform:animal_sex = "" ;
platform:animal_stage = "" ;
```

**Comment by iamchrisser** [comment]
This seems like a workable solution.  Do we want `animal_stage` or `animal_life_stage` like MM mentioned above? The latter matches [this term](https://vocab.nerc.ac.uk/collection/MVB/current/MVB000018/2/) from Movebank

**Comment by MathewBiddle** [comment]
Latter `animal_life_stage`

**Comment by iamchrisser** [comment]
Each of these attributes has been added in the recent commit.

**Comment by mmckinzie** [comment]
@iamchrisser @MathewBiddle I know there has been a lot of back and forth on how best to handle reporting these vales and whether or not they should be reported within the attributes or variables, but to better align with other national telemetry templates, AniBOS and nc-eTAG specifications can we remove these from the variables and add as global attributes in this form:

animal_ageclass_capture
animal_ageclass_unit_capture
animal_length_capture
animal_length_type_capture
animal_length_type_vocabulary
animal_length_unit_capture
animal_lifestage_capture
animal_lifestage_vocabulary
animal_sex_capture
animal_sex_vocabulary
animal_weight_capture
animal_weight_unit_capture

This also aligns with changes Dave A. recently made to the Reg App

**Comment by iamchrisser** [comment]
Seems weird to pull all of this animal/platform metadata out of those variable attributes and put it in the global atts, but this is an easy change. @MathewBiddle, what's your opinion on this?

**Comment by iamchrisser** [comment]
OK, we'll move these into global attributes.

**Comment by MathewBiddle** [comment]
Not a huge fan of putting this in global attributes, but it's fine.
