### ISSUE TITLE
add uuid attribute

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#17]
From NCEI netCDF template:

Machine readable unique identifier for each netCDF file. A new uuid should be created whenever the netCDF file is changed. Review the history attribute listed below for further information about tracking older versions of the data file.

From Wikipedia: A UUID is a 16-byte (128-bit) number. The number of theoretically possible UUIDs is therefore about 3 × 1038. In its canonical form, a UUID consists of 32 hexadecimal digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 digits and 4 hyphens). (e.g., 550e8400-e29b-41d4-a716-446655440000) http://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by iamchrisser** [comment]
We did have this field, but were populating it with the same value we used in the `platform_id` and `platform_name` fields. I've put this attribute back in with a uuid, but it's not something we're tracking internally - just something that will get sent along to the NCEIj.

**Comment by MathewBiddle** [comment]
Looks good! NCEI and other users can benefit from this file level unique identifier. I just came across a need for this in another case.

https://github.com/ioos/ioos-atn-data/blob/3c36a14f87c54c6ba154c822514a9072fb38181f/data/examples/atn_trajectory_template_ncdump.txt#L258
