### ISSUE TITLE
global attribute ncei_template_version

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#18]
should be `NCEI_NetCDF_Trajectory_Template_v2.0`
https://github.com/ioos/ioos-atn-data/blob/3c36a14f87c54c6ba154c822514a9072fb38181f/data/examples/atn_trajectory_template_ncdump.txt#L284

**Comment by iamchrisser** [comment]
Oops. this was a typo in my notebook. Fixed now.

**Comment by iamchrisser** [comment]
Fixed in the recent commit.
