### ISSUE TITLE
long_name attributes

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#19]
We should update the `long_name` attributes to have some human readable string.

id | name | variable | value
---|-------|----------|-------
1|long_name|trajectory|trajectory identifier
6|long_name|time|Time
2|long_name|z|depth
3|long_name|lat|Profile Location
3|long_name|lon|Profile Location
1|long_name|location_class|Location Quality Code
2|long_name|deploy_id|Platform identifier
1|long_name|instrument|Instrument
1|long_name|type|Type of location
2|long_name|error_radius|Error radius
2|long_name|semi_major_axis|Error semi-major axis
2|long_name|semi_minor_axis|Error semi-minor axis
2|long_name|ellipse_orientation|Ellipse orientation
2|long_name|offset|Offset
2|long_name|offset_orientation|Offset orientation
1|long_name|comment|Comment
3|long_name|crs|http://www.opengis.net/def/crs/EPSG/0/4326
0|long_name|instrument_location|instrument
1|long_name|platform|NOT PROVIDED IN REG APP - SHOULD BE THE VALUE OF THE 'Animal ID' FIELD
3|long_name|qartod_rollup_flag|
3|long_name|qartod_speed_flag|
3|long_name|qartod_location_flag|
3|long_name|qartod_time_flag|
1|long_name|taxon_name|most precise taxonomic classification
1|long_name|taxon_lsid|Namespaced Taxon Identifier

Some of these are less then helpful.

**Comment by MathewBiddle** [comment]
NCEI's guidance 
> While long_name is intended for a phrase or a one line description of what the data represents, comment could be much longer and is intended to provide in greater detail any miscellaneous information important to interpret the data.

**Comment by iamchrisser** [comment]
Most of these are updated in the most recent commit, but not all. I'm waiting to hear back about a few things, and some of these seem adequate to me. Open to suggestions for how these can be improved though.

**Comment by MathewBiddle** [comment]
Lets leave this open. I'll create an updated table with the new long_name attributes and add it here.
