### ISSUE TITLE
add global attributes for creator and contributor id, id sources

### ISSUE THREAD

**Issue by iamchrisser** [ioos/ioos-atn-data#24]
We want to include ORCIDs or Researcher IDs for creators and contributors. We don't have all the details worked out yet, but this seems to be a good place to keep track of this need the decisions we make along the way. As a starting point, we're talking about 4 attributes:
> contributor_id
> contributor_id_source
> creator_id
> creator_id_source

A few questions:
1. Is 'source' the right term, or do we want to use 'namespace'  or 'authority' instead? 
2. Do we need to allow more than one identifier for each individual listed? We spoke about this question on the call and seemed to agree that we didn't want/need to support  more than 1 id per person. Do we still all agree on this? I hope so.
3. In the 'id_source' attributes, do we want to use terms like 'ORCID' and 'ResearcherID', or use links to those orgs/services? I'd vote for links.

**Comment by MathewBiddle** [comment]
I posted this proposal to the ESIP Marine Data Cluster and received some good feedback.

I think we might be able to simplify this by using the existing `creator_url` ([ACDD 1.3](https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3#creator_url)) and `contributor_url` ([IOOS Metadata Profile v1.2](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#attribution)).

We have to deviate slightly from the IOOS Metadata Profile recommendations on `creator_url`, but we are still in line with ACDD 1.3. I'll iterate with @mwengren on that.

IOOS Metadata Profile guidance on `creator_url`:
>The URL of the _institution_ that collected the data. Note that this should always reference an institution URL, and not a personal URL, even if `creator_type=person`.

We should populate those attributes with the **full uri** as [recommended by ORCiD](https://info.orcid.org/brand-guidelines/#digital-publications). Still unsure about ResearcherID and how they recommend citing it.

From the ORCID guidance:
## Digital publications
The ORCID iD should be displayed in all formats of the article (i.e., HTML, PDF, EPUB) as well as related metadata.

* The ORCID identifier should be displayed as the full iD URI, with https scheme (unless https is not possible for technical reasons):
   * https://orcid.org/0000-0002-1825-0097


So, now lets look at an example:
### Creator
```
		:creator_name = "Mathew Biddle" ;
		:creator_email = "mathew.biddle@noaa.gov" ;
		:creator_country = "USA" ;
		:creator_type = "person" ;
		:creator_url = "https://orcid.org/0000-0003-4897-1669" ;
		:creator_state = "" ;
		:creator_city = "" ;
		:creator_address = "" ;
		:creator_postalcode = "" ;
		:creator_institution = "NOAA NOS, Integrated Ocean Observing System" ;
		:creator_sector = "" ;
```
### Contributor
```
		:contributor_email = "fcontributor1@noaa.gov, fake.contributor2@somthing.tld" ;
		:contributor_name = "fake contributor1, fake contributor2" ;
		:contributor_role = "mediator, contributor" ;
                :contributor_url = "https://orcid.org/[fakecontrib1_orcid], https://orcid.org/[fakecontrib2_orcid]"
		:contributor_role_vocabulary = "http://vocab.nerc.ac.uk/collection/G04/current/" ;
```

**Comment by shane-axiom** [comment]
The downside I see with the approach of leveraging `creator_url` and `contributor_url` is that it limits the identifier values to URLs and doesn't allow the use of other value types (including URNs). Maybe that's not a big deal?

In other words, in the case of ResearcherID, is it ok to force the use of creator_url `https://publons.com/researcher/D-8052-2011/`, rather than creator_id `D-8052-2011` and creator_id_namespace `ResearcherID`? Do we know of any systems that favor non-URL identifiers?

**Comment by mmckinzie** [comment]
@MathewBiddle just wanted to confirm if attributes should be contributor_url and creator_url OR contributor_institution_url and creator_institution_url?

**Comment by mmckinzie** [comment]
we also need to remove contributor_id_source and creator_id_source

**Comment by iamchrisser** [comment]
The only thing left to resolve here is whether we want to add creator_institurion_url. My feeling is that we should ask for it, but not require it.

**Comment by iamchrisser** [comment]
We'll keep this.
