### ISSUE TITLE
ATN satellite telemetry data flow diagram update

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#27]
Need to update the data flow diagram [here](https://github.com/ioos/ioos-atn-data/blob/main/README-ArchiveSOP.md).

Current draft:

![ATN_Data_Flow](https://user-images.githubusercontent.com/8480023/142282660-b3e36abf-ad43-43d1-9126-4827a3f056bf.png)

@mmckinzie @iamchrisser comments welcome.

**Comment by mmckinzie** [comment]
@MathewBiddle can you provide me with an editable version of above diagram? So I can provide some suggested modifications.

**Comment by MathewBiddle** [comment]
@mmckinzie I've seen various incarnations of a flow diagram for ATN. Is the diagram linked here representative of what we think is happening? 

Do you have something that is more appropriate?

I've seen this slide show up a couple times 
![image](https://user-images.githubusercontent.com/8480023/224739741-3ad9b0d3-2f43-413b-b836-1429e6cad05a.png)

**Comment by MathewBiddle** [comment]
```mermaid
flowchart TD

A([Satellite Tag Deployment])
B([Ingest into ATN])
C([Axiom Workspace])
D([NCEI])
E([Darwin Core Alignment])
F([IPT OBIS-USA])
G([ATN Portal])

A --> B
B --> C
C --> D
D --> E
E --> F
C --> G
```

**Comment by MathewBiddle** [comment]
We don't need to worry about NDBC/GTS in this diagram as we're only looking at satellite telemetry data, not profile data.

**Comment by mmckinzie** [comment]
Profile data are satellite telemetry data...profiling tags (a type of satellite tag) will have both a trajectory file and a profile file, these data are handled separately but must remained linked. All satellite telemetry tags/datasets will always include a trajectory file but not all satellite tags/dataset will also include profile data (only select tag types from select manufacturers).

**Comment by MathewBiddle** [comment]
Ahh, thank you @mmckinzie for clarifying. I still have a lot to learn. Updated diagram coming soon.

**Comment by MathewBiddle** [comment]
```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart TD

A([Satellite Tag Deployment])
B([ATN])
D([NCEI])
E([Darwin Core Alignment])
F([IPT OBIS-USA])
G([ATN Portal])
H([NDBC])
I([GTS])

A --> B
B -- Data released from embargo --> D
D --> E
E --> F
B --> G
B -- Profiling Tags --> H
H --> I
F --collection--> D
```

**Comment by MathewBiddle** [comment]
This high level diagram should go on the landing page at https://ioos.github.io/ioos-atn-data/

follow the guidance at https://github.com/ioos/documentation-theme-jekyll/pull/16#issue-2088773574 (soon to be added to our docs https://github.com/ioos/ioos-documentation-jekyll-skeleton/pull/17)

**Comment by MathewBiddle** [comment]
Adding in Federal Catalogs:

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart TD

A([Satellite Tag Deployment])
B([ATN])
D([NCEI])
E([Darwin Core Alignment])
F([IPT OBIS-USA])
G([ATN Portal])
H([NDBC])
I([GTS])
J[(NOAA OneStop)]
K[(data.gov)]
L[("Commerce
Data Hub")]

A --> B
B -- Data released from embargo --> D
D --> E
D --> FC
E --> F
B --> G
B -- Profiling Tags --> H
H --> I
F --collection--> D


subgraph FC [U.S. Federal Catalogs]
J
K
L
end

```

**Comment by MathewBiddle** [comment]
reopening because this should include a pathway to the IOOS Data Catalog.

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#007396',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#003087',
      'lineColor': '#003087',
      'secondaryColor': '#007396',
      'tertiaryColor': '#CCD1D1'
    },
   'flowchart': { 'curve': 'basis' }
  }
}%%

flowchart TD

A([Satellite Tag Deployment])
B([ATN])
D([NCEI])
E([Darwin Core Alignment])
F([IPT OBIS-USA])
G([ATN Portal])
H([NDBC])
I([GTS])
J[(NOAA OneStop)]
K[(data.gov)]
L[("Commerce
Data Hub")]
M[("IOOS Data Catalog
(data.ioos.us)")]

A --> B
B -- Data released from embargo --> D
D .-> E
D --> FC
E .-> F
B --> G
B -- Profiling Tags --> H
B .->|Data released from embargo| M
M --> FC
H --> I
F --collection--> D


subgraph FC [U.S. Federal Catalogs]
J
K
L
end

```
