### ISSUE TITLE
Variable dimensions 

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#3]
### Container variables
The following variables should be container variables and not have a dimension (similar to the **trajectory** variable): 
https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L73
https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L152
https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L144

### String variables
The following variables should have a dimension of the maximum possible string length. According to the [CF documentation on Data Types](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#_data_types) the dimension should be `large enough to contain the longest string in the variable`  (in this case 41 would be sufficient for both since `urn:lsid:marinespecies.org:taxname:137080` is 41 characters long):
https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L177

https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L180

**Comment by MathewBiddle** [comment]
from @iamchrisser 
* I've converted 'instrument_tag' and 'platform' to container variables like Matt suggested. 'instrument_location' is written into the file before I get my hands on it, and I don't think the python netCDF4 library lets me delete or re-dimension an existing variable. This one has to stay as in in our example file until we make the change further back in the pipeline. That'll be something the devs will need to do. Should we keep this in the file as is, or remove it from the example? I guess I'd prefer the latter, as that seems like a better way to ensure it isn't forgotten about later on.
* taxon_name and taxon_lsid are now string variables.

**Comment by iamchrisser** [comment]
Shoot, I meant the former, that we should keep the mis-dimensioned instrument_location variable in the templates for now.

**Comment by iamchrisser** [comment]
OK, slight progress on this. Now `instrument_tag`, `instrument_location`, and `platform` are all container variables. I am still limited by the python netcCDF4 library and can't delete `instrument`. I guess xarray can do that, so once I have some more time to look into this I'll learn xarray and fix this. For now, it's there as a bonus, or as graffiti.

**Comment by MathewBiddle** [comment]
Looks good! I'll leave this open until we can resolve that `instrument` variable.
