### ISSUE TITLE
remove creator address attributes

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#32]
I know I am the one who originally suggested we add these attributes (see below), but the more I think about it, the more I think they are unnecessary and likely OK to remove.

creator_address
creator_city
creator_state
creator_postalcode

**Comment by iamchrisser** [comment]
Yup, works for me, too. I'll close this once it's done.

**Comment by iamchrisser** [comment]
Done. @mmckinzie, dDo we also want to delete `creator_country`, or should we leave that in the template? I think we should drop it, but want to check in since you didn't list it.

**Comment by iamchrisser** [comment]
I'm going to remove it. Reopen this issue if this attribute needs to stay.
