### ISSUE TITLE
misc creator attributes

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#33]
These are only recommendations but to be more consistent bw what is reported for creator vs contributor(s) and again to better align the AniBOS and others can we consider adding the following attributes:

creator_role
creator_role_vocabulary
creator_sector_vocabulary

**Comment by MathewBiddle** [comment]
Thought those were in there... Sounds good to me.

**Comment by iamchrisser** [comment]
I've added these to the template as global attributes, but they'll have empty values in files we deliver until we have more of Dave's time to update the ADR with the appropriate vocabs.

**Comment by mmckinzie** [comment]
@iamchrisser OK thanks for adding these to the template as global attributes and roger that regarding fields being blank until the ADR can be updated.

**Comment by iamchrisser** [comment]
Sounds like there's nothing to do on this issue for now. Let's leave this open until we have the $ to do the ADR updates needed to address it.
