### ISSUE TITLE
updated vendor and vendor_id

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#34]
Can we change vendor to instrument_manufacturer and vendor_id to manufacturer_id?

**Comment by MathewBiddle** [comment]
I see `vendor_id`
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L297

but not `instrument_manufacturer`

Change it to whatever makes the most sense to ATN and document it somewhere.

**Comment by iamchrisser** [comment]
Will this always be the tag manufacturer? I was thinking of this as the org that maintains the data system from which we get the data. Often that's the same as the tag manufacturer, but I'm not sure that it always is. @mmckinzie, you probably know that better than I do.

**Comment by iamchrisser** [comment]
ping @mmckinzie. Are we sure that vendor and manufacturer will always be the same thing?

**Comment by mmckinzie** [comment]
@iamchrisser That was not how I had been interpreting those attributes nor how other networks had been interpreting them but I see your point and no the vendor and the manufacturer may not always be the same (although more often than not) and considering the manufacturer is listed within the instrument variables, I agree these should be left as vendor and vendor id and I'll update my attribute description notes accordingly as you suggested above (i.e., org that maintains the data system from which we get the data and their corresponding unique id).

**Comment by iamchrisser** [comment]
@mmckinzie could you share the attribute description notes you mentioned in your prior comment? I want to make sure we're on the same page for all the attributes.
