### ISSUE TITLE
misc instrument attributes

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#35]
Can we add these to the global attributes?

instrument_model
instrument_sensor_type
instrument_serial_number

may want to consider also adding instrument_sensor_type_vocabulary (http://vocab.nerc.ac.uk/collection/MVB/current/MVB000170/) and instrument_model_vocabulary (http://vocab.nerc.ac.uk/collection/L22/current/)

if we used the model vocab, we may need to report the tool id in instrument_model over actual manufacturer model type, i.e., report TOOL0873 instead of GPS SRDL. Most of the SMRU tag types are already included but only miniPATs for wildlife computers, so we would have to request the other WC tag types/models get added.

**Comment by MathewBiddle** [comment]
That information should already be in the appropriate instrument variable, for example:
https://github.com/ioos/ioos-atn-data/blob/2dcafb8ee6c47b01e4ca4f8d6042ae07652288e4/data/atn_trajectory_template_ncdump_20211006.txt#L177-L184

As far as adding the vocabulary attributes, yes the more we can appropriately define these attributes the better.

On your last note, note sure I follow 100% but I would be hesitant to have the ATN archive process dependent on if an appropriate term gets added to a controlled vocabulary. Yes, propose the term and follow through with that, but remember we can always go back and update files when we get more information. So, don't let our progress stall waiting for that additional metadata.

**Comment by iamchrisser** [comment]
@mmckinzie let's save thise for v2. Adding new vocabs will need to wait until we have more of Dave's time.

**Comment by mmckinzie** [comment]
@iamchrisser @MathewBiddle Roger that regarding adding vocabs until V2. I am OK with that.  Also fine to leave instrument attributes as is in variables over moving to the global attributes. I am going to close this issue.
