### ISSUE TITLE
gts_insert attribute

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#36]
gts_insert (true or false) is marked as required, if applicable....and while clearly not applicable to the trajectory template, it will be for the profile template and it would be nice if the global attributes were the same bw the two templates, so I think we should add it to the trajectory template and just report false by default.

**Comment by MathewBiddle** [comment]
I don't agree. If the attribute is not necessary for these data, then why would you add it?

**Comment by MathewBiddle** [comment]
Note, it should be `gts_ingest` See https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#requirements-for-ioos-dataset-ndbcgts-ingest

**Comment by iamchrisser** [comment]
I think we agreed not to include this on our last call. Assuming I have that right, I'll mark this as closed.
