### ISSUE TITLE
qc_manual attribute?

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#37]
qc_manual attribute is required within others templates, so wondering if it would be good to add to ours and provide URL to QARTOD manual?

**Comment by MathewBiddle** [comment]
Doesn't hurt. However, I would recommend to also put it in the `references` attribute for the flag variable. According to [CF](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#description-of-file-contents):
> references
>   Published or web-based references that describe the data or methods used to produce it.

See [PacIOOS example](https://pae-paha.pacioos.hawaii.edu/erddap/info/WQB-04/index.html) and screenshot
![image](https://user-images.githubusercontent.com/8480023/161994167-f97c0a00-b7f6-474b-a740-671fb85c7f6b.png)

See [SECOORA example](https://erddap.secoora.org/erddap/info/edu_usf_marine_comps_c10/index.html) and screenshot
![image](https://user-images.githubusercontent.com/8480023/161994963-b3f424f8-0514-4799-b340-79d9b6e5947c.png)

**Comment by mmckinzie** [comment]
I am fine with that.

**Comment by iamchrisser** [comment]
We've agree to leave this in the `references` attribute for each variable.
