### ISSUE TITLE
Example files for NCEI review?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#44]
Just checking in on our progress for creating the example files for NCEI review. Anything we can do to help move it along?

**Comment by MathewBiddle** [comment]
Any updates on the example file?

**Comment by MathewBiddle** [comment]
@iamchrisser @mmckinzie Just got off a call with NCEI. We are looking good to get everything set up for the NCEI sprint coming up. NCEI is working on drafting up the archive automation SOP at the moment. It would greatly help NCEI if there were a few example files from which they can develop the SOP. Let me know if I can help move the needle on this.

**Comment by mmckinzie** [comment]
@iamchrisser Anything you need from me or I can do to help?

**Comment by iamchrisser** [comment]
I'll send at least one example file by the end of the day today.

**Comment by MathewBiddle** [comment]
closed with https://github.com/ioos/ioos-atn-data/commit/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe
