### ISSUE TITLE
filename convention

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#46]
From NCEI:
>What are your thoughts on structuring the file names? Can we set the naming convention to include the start and end dates of the data?

@MathewBiddle idea:
`atn_[ptt id]_[animal common name]_[start date]_[end date].nc`

for example,
`atn_195533_grey_seal_2020-01-30_2020-06-15.nc`

@mmckinzie comment:
I wouldn't recommend using the data start and ends dates as they do not typically align with the actual deployment window (biologically relevant period of data) and likely to lead to confusion.

**Comment by mmckinzie** [comment]
While I have concerns about using the start and end dates of the date files themselves over the deployment window, it appears that is the only option, so likely the best path forward.  

As previously discussed, I also think we should add 'trajectory' or 'profile' to the file name. 

atn_[ptt id]_[animal common name]_trajectory_[start date]_[end date].nc or 
atn_[ptt id]_[animal common name]_profile_[start date]_[end date].nc    

for example, 
atn_195533_grey seal_trajectory_2020-01-30_2020-06-15.nc and
atn_195533_grey seal_profile_2020-02-01_2020-06-05.nc

**Comment by MathewBiddle** [comment]
@mmckinzie thanks for adding this context. I do have one recommendation that we replace any spaces with underscores in the filename (maybe even remove the hyphens). Typically those characters don't work well across OS's. 

So, the examples would look like:

`atn_195533_grey_seal_trajectory_20200130_20200615.nc` and
`atn_195533_grey_seal_profile_20200201_20200605.nc`

Thoughts?

**Comment by mmckinzie** [comment]
@MathewBiddle I think that is a good suggestion. I agree. Examples above look good to me.

**Comment by iamchrisser** [comment]
These suggestions look good to me. I formatted the filename for the newest example file like those in Matt's comment above.

**Comment by MathewBiddle** [comment]
reopening this one as there were concerns from NCEI about how we could encounter name conflicts. I'll try to summarize the concerns below:

There could be a case where a specific tag (`ptt`) is redeployed on an animal with the same `common name`. The only way NCEI would know there is a completely separate deployment is if they did some checking on the dates in the filename. However, the dates we are using in the filename are the dates of **data coverage** not deployment. So, those dates will be different between `trajectory` files and `profile` files.

So, this all boils down to how can we configure the filename to uniquely identify a set of files (trajectory, profile, and in the future foi gras) as associated with a specific deployment. 

Below is an example of the conundrum we're in:

These files are hosted on the WAF for NCEI to pick up:
```
atn_195533_grey_seal_trajectory_20200130_20200615.nc
atn_195533_grey_seal_profile_20200201_20200605.nc
atn_195533_grey_seal_trajectory_20200616_20200715.nc
atn_195533_grey_seal_profile_20200606_20200622.nc
```

There were two proposals during the discussion.
1. Use the deployment dates (which are manually provided and reviewed by Megan)
   ```
   atn_195533_grey_seal_trajectory_20200201_20200615.nc
   atn_195533_grey_seal_profile_20200201_20200615.nc
   atn_195533_grey_seal_trajectory_20200616_20200715.nc
   atn_195533_grey_seal_profile_20200616_20200715.nc
   ``` 
2. Axiom defines the deployments in their WAF structure and NCEI follows that structure:
   ```
   deployment_1/
      |--- atn_195533_grey_seal_trajectory_20200130_20200615.nc
      `--- atn_195533_grey_seal_profile_20200201_20200605.nc
   deployment_2/
      |--- atn_195533_grey_seal_trajectory_20200616_20200715.nc
      `--- atn_195533_grey_seal_profile_20200606_20200622.nc
   ```

**Comment by iamchrisser** [comment]
After talking with Kyle, it sounds like we do prefer the second option, with a folder in the WAF for each deployment. 

Also on the topic of the WAF, we want to go with a standard WAF, rather than use ERDDAP's virtual filesystem as has occassionally been discussed in our calls.

**Comment by MathewBiddle** [comment]
filename convention is officially:

`atn_`[_ptt id_]`_`[_animal common name_]`_trajectory_`[_start date_]-[_end date_]`.nc`

eg. `atn_45866_great-white-shark_trajectory_20090923-20091123.nc`

Need to add this to https://github.com/ioos/ioos-atn-data/blob/gh-pages/_docs/atn-sat-telem-specification-v1-0.md
