### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#48]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L322

**Comment by iamchrisser** [comment]
Lol. This typo must be in the file creation script that makes the initial netCDF file from what we get from the data provider. This is fixed in the current metadata improvement script.
