### ISSUE TITLE
add long_name and comment describing that this is the unique value to communicate 

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#51]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L106-L108

**Comment by iamchrisser** [comment]
I added these attributes today, as:

> ncfile.variables["ptt"].setncattr("long_name","Platform Transmitter Tag code.")
> ncfile.variables["ptt"].setncattr("comment","PTT code for this deployment. PTT codes may be used on multiple deployments, but  not concurrently. When combined with deployment dates, PTTs can uniquely identify a deployment.")
