### ISSUE TITLE
gpe_u and gpe_msd variables

### ISSUE THREAD

**Issue by iamchrisser** [ioos/ioos-atn-data#53]
We had talked on our call about keeping these in the files to avoid losing any information. After doing some digging, it looks like these are deprecated, historical variables that aren't used anymore. I now think it best to delete these variables. 

This issue describes these variables as deprecated, and states that they're no used in any of the models used to generate location estimates: https://github.com/camrinbraun/HMMoce/issues/18#issuecomment-596639779

**Comment by mmckinzie** [comment]
I am OK with deleting these variables
