### ISSUE TITLE
creator_institution, remove 'role' report only 'institution'

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#60]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L324

**Comment by mmckinzie** [comment]
Can we remove creator role, i.e., 'Program Lead" and only list reported organization/institution? i.e., 'Marine Turtle Biology and Assessment Program, NOAA Pacific Islands Fisheries Science Center'

**Comment by iamchrisser** [comment]
Why do you want to remove `creator_role`? This is something that we can take from the Reg App, where we have defined PI and Data Manager roles.
