### ISSUE TITLE
deployment start and end date format

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#62]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L335

https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L336

**Comment by mmckinzie** [comment]
Can we update datetime format to 'yyyy-mm-dd-Thh:mm:ssZ'?

**Comment by iamchrisser** [comment]
Seems fine, if a little harder for people to read. I'll leave this open for IOOS/NCEI folks to comment on.
