### ISSUE TITLE
deployment id missing

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#63]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L332

**Comment by mmckinzie** [comment]
deployment id should be = 5f08ee316321be13bc7fbc37

**Comment by iamchrisser** [comment]
ok, added to the script.
