### ISSUE TITLE
vertical_crs correct?

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#64]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L268

**Comment by mmckinzie** [comment]
Is this correct?
 Should this be = "EPSG:5831"

**Comment by iamchrisser** [comment]
Maybe? That's what we will use when there are depth values in the profile typed files, but there's no vertical component to these trajectory files. Maybe it would be better to remove that field?
