### ISSUE TITLE
Missing 'hash value'

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#66]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L299

**Comment by mmckinzie** [comment]
example is missing 'hash value', i.e., d148c911-209e-44b1-a708-c155bbe4c694

infoUrl = "https://www.portal.atn.ioos.us/#metadata/d148c911-209e-44b1-a708-c155bbe4c694/project"

**Comment by iamchrisser** [comment]
There no mechanism to get this automatically so I was just leaving this attribute with the stub url while we continue to spec out the template. I've added this to the script.
