### ISSUE TITLE
Should these only be GCMD keywords?

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#67]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L301

**Comment by mmckinzie** [comment]
Should this attribute only report GCMD keywords?

Do we need to report the whole string? 

e.g.,  EARTH SCIENCE > AGRICULTURE > ANIMAL SCIENCE > ANIMAL ECOLOGY AND BEHAVIOR, EARTH SCIENCE > BIOSPHERE > ECOLOGICAL DYNAMICS > SPECIES/POPULATION INTERACTIONS > MIGRATORY RATES/ROUTES, EARTH SCIENCE > OCEANSEARTH SCIENCE > CLIMATE INDICATORS > BIOSPHERIC INDICATORS > SPECIES MIGRATION, EARTH SCIENCE > OCEANS, EARTH SCIENCE > BIOLOGICAL CLASSIFICATION > ANIMALS/INVERTEBRATES

**Comment by iamchrisser** [comment]
That's a question for NCEI folks, but they've not been active on this repo. I do know that that string, and the keyword hierarchy that it represents, can change between GCMD versions.

**Comment by MathewBiddle** [comment]
@iamchrisser pinged NCEI. Probably need to discuss this at our next tag up.
