### ISSUE TITLE
platform type and vocab

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#68]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L305

https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L304

**Comment by mmckinzie** [comment]
Wrong vocab listed. Use http://vocab.nerc.ac.uk/collection/L06/current/

Therefore platform_type = "organism" for this loggerhead example

**Comment by iamchrisser** [comment]
You say 'for this example' but we want a vocab we can use for every file we create/improve. Can we just hard-code this as 'organism' for every deployment?
