### ISSUE TITLE
Update summary?

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#69]
https://github.com/ioos/ioos-atn-data/blob/012da2c01530110d5ffe6f1e0f45ed4bb4aba4fe/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L350

**Comment by mmckinzie** [comment]
Can we also update summary to reflect desired changes to 'title' and 'citation', i.e., move ptt id to after 'tag', report deployment window and add deployment id.  

e.g., Wildlife Computers SDR tag (ptt id 22275) deployed on a loggerhead turtle (Caretta caretta) by Summer Martin in North Atlantic Ocean from 2000-07-17 to 2001-07-24.

**Comment by iamchrisser** [comment]
I have no problem with this.
