### ISSUE TITLE
animal length variables

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#70]
https://github.com/ioos/ioos-atn-data/blob/8e02654721c02932b582791b35ff3e79e5e896ab/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L237

**Comment by mmckinzie** [comment]
need to include animal_length, animal_length_units and animal_length_type variables 

animal length units will not always be cm and length type will also vary from deployment to deployment and needs to be reported.

**Comment by MathewBiddle** [comment]
Will the length measurements within each deployment be consistent? The units can change between files. It would almost be better, if there were two lengths measured, to have them in two different length variables (animal_length_1, animal_length_2, etc.) with appropriate long_name and unit attributes describing how the length was measured.

**Comment by iamchrisser** [comment]
My memory and the template spreadsheet agree with Matt's suggestion. I don't recall ever vreaking out `animal_length_units` or `animal_length_type` as their own variables. Both of those pieces of info are present on the `animal_length_n` variable.
