### ISSUE TITLE
add animal age class variables

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#71]
variables animal_age_class and animal_age_class_units are missing from the loggerhead example

**Comment by iamchrisser** [comment]
Is this different from `animal_life_stage`? I don't recall us ever talking about `animal_age_class`. Easy to add though, if that's what we want to do.

**Comment by MathewBiddle** [comment]
See my comment at https://github.com/ioos/ioos-atn-data/issues/70#issuecomment-1404239395 regarding where `units` should go.
