### ISSUE TITLE
wrong animal id report in container variables

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#72]
https://github.com/ioos/ioos-atn-data/blob/8e02654721c02932b582791b35ff3e79e5e896ab/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L1538

**Comment by mmckinzie** [comment]
Wrong id reported, this variable should report BP6772 not A6173

**Comment by iamchrisser** [comment]
ok. fixed in the script.
