### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#73]
https://github.com/ioos/ioos-atn-data/blob/8e02654721c02932b582791b35ff3e79e5e896ab/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L1534

**Comment by mmckinzie** [comment]
Should this variable report something different from instrument_tag? 

Maybe report "Argos doppler shift" or something similar?

**Comment by iamchrisser** [comment]
I don't see that information in the metadata in the reg app or in the file that I started with. Is the argos location device a separate thing applied to the animal, or is it built into the WC tag? If it's built into the WC tag, then lising the WC tag for `instrument_location` seems ok to me.
