### ISSUE TITLE
report not provided or report whole string

### ISSUE THREAD

**Issue by mmckinzie** [ioos/ioos-atn-data#74]
https://github.com/ioos/ioos-atn-data/blob/8e02654721c02932b582791b35ff3e79e5e896ab/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L1542

https://github.com/ioos/ioos-atn-data/blob/8e02654721c02932b582791b35ff3e79e5e896ab/templates/atn_22275_loggerhead_turtle_trajectory_19990720_20040226_ncdump.txt#L1544

**Comment by mmckinzie** [comment]
Can we report 'not provided' if metadata are not available for that specific deployment in the Reg App, otherwise report the whole string including units and type, when applicable.

e.g., animal_length =  48.9 cm curved carapace length
animal_weight = 98.5 kg

**Comment by MathewBiddle** [comment]
humm, what about adding a `_FillValue` attribute for those variables. See https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#missing-data

**Comment by iamchrisser** [comment]
Seems to me that having a descriptive string as the value for these variables makes it harder to compare animal mass and length across many files, I'm not sure how realistic or useul a usecase that is. I'll defer to you to on this one.
