### ISSUE TITLE
Add a note about attributes not in spec to webpage

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#78]
somewhere on https://ioos.github.io/ioos-atn-data/atn-sat-telem-specification-v1-0.html we should have a note along the lines of:
> Included attributes not described in the[ ATN satellite telemetry specifications](https://ioos.github.io/ioos-atn-data/) (https://ioos.github.io/ioos-atn-data/) are unverified and may not follow dataset conventions or vocabularies.

**Comment by iamchrisser** [comment]
Done. It's point #5 in the first numbered list.
https://ioos.github.io/ioos-atn-data/atn-sat-telem-specification-v1-0.html

**Comment by MathewBiddle** [comment]
https://github.com/ioos/ioos-atn-data/commit/b595a29a17c57a1678433703e999e0c85896fd0c
https://github.com/ioos/ioos-atn-data/commit/0150ff2992840053a569c5bd43b158387b834ef5
