### ISSUE TITLE
comments on the platform variable

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-atn-data#8]
1. I don't think we need the attributes `platform_vocabulary` and `platform_type`. The term `animal` doesn't exist in the [IOOS Platform vocabulary](https://mmisw.org/ont/ioos/platform). Plus I don't think of that as an authoritative vocabulary for these terms. We should be referencing something more authoritative, like GCMD for this content. I did some digging through the [NERC Vocabulary Server](https://vocab.nerc.ac.uk/search_nvs/) and couldn't find an appropriate, generic, term. 
https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L152-L176

1. The `cf_role` attribute should only be associated with the `trajectory` variable. See the [CF1.7 guidance on coordinates and metadata](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#coordinates-metadata)
1. The `long_name` should be the common name for the species, in my opinion.
1. Can we change the variable name to `animal`? There are [no hard-fast rules on variable names](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#variables), so I think this adjustment would make it clearer that the variable is documenting the animal, and that animal is treated as a platform.

**Comment by MathewBiddle** [comment]
From @iamchrisser 
* Request to remove the attributes `platform_vocabulary` and `platform_type` - I don't feel like it's up to me to say yes or no to this. We knew when we started this that 'animal' was missing from the IOOS vocab, but I think we hoped it would be added later. I'm not sure how to make that happen, but if that's the issue, we can pursue that. On the other hand, If Matt is comfortable speaking for IOOS and saying that we don't need it, then I'm comfortable removing it. Any objections to my reasoning, or to getting rid of it?
* The `cf-role` attribute is now associated with the value of the trajectory variable as suggested.
* Associate `long_name` attribute with the common name of the species - I think we're on board with this, but I haven't made the change yet. I want MM and the ATN office to weigh in on this. 
* Change variable name to animal - this also seems OK to me, but I'd like the ATN office to approve or deny this.

**Comment by mmckinzie** [comment]
I need to think about this more, before I can respond. I agree we need to be consistent but I am on the fence about whether or not to keep as platform or update variable to animal.

**Comment by MathewBiddle** [comment]
@mmckinzie @iamchrisser what about this option. We keep the `platform_type` and `platform_vocabulary` attributes and we populate them with one of these options:
A.
```
platform_type = "EARTH SCIENCE > BIOLOGICAL CLASSIFICATION > ANIMALS/INVERTEBRATES" ;
platform_vocabulary = 'NASA Global Change Master Directory v10.1"; 
```
B.
```
platform_type = "organism" ;
platform_vocabulary = 'SeaVoX Platform Categories v17"; 
```
Note to B. You can see more options for the SeaVox Vocabulary [here](http://vocab.nerc.ac.uk/collection/L06/current/). Like `land-sea mammals` or `fish` or `cetacean`.

**Comment by mmckinzie** [comment]
I am also fine with Option A.

**Comment by mmckinzie** [comment]
@iamchrisser @MathewBiddle Is it still possible to change the platform variable name to animal? I agree with Matt's earlier statement that this change would make it clearer that the variable is documenting the animal, and that animal is treated as a platform.

**Comment by iamchrisser** [comment]
`platform` changed to `animal` in the most recent example.

**Comment by iamchrisser** [comment]
Hold on. @MathewBiddle, I think I made a mistake here. Weren't these supposed to be global attributes?

**Comment by mmckinzie** [comment]
@MathewBiddle @iamchrisser IOOS has updated their recommendations surrounding platform vocab, making it OK to use: http://vocab.nerc.ac.uk/collection/L06/current/ 

So I think we should keep the platform attribute, reporting appropriate values from platform_vocabulary and then remove plaform_type attribute.

**Comment by iamchrisser** [comment]
so to clarify, we want to have the following global attributes:
`platform: [value from NERC/SeaVox platform vocab]`
`platform_id: [animal lsid ]`
`platform_name:[animal scientific name]`
`platform_vocabulary: "http://vocab.nerc.ac.uk/collection/L06/current/"`

Does that look right? If yes `platform_name` is always going to have the same value as `animal_scientific_name`. Do we want to either:
1. drop `animal_scientific_name` and change `animal_common_name` to `platform_common_name`?
2. drop `platform_name` and leave `animal_scientfic_name` and `animal_common_name` as they are?
3. include all three attributes?

**Comment by iamchrisser** [comment]
On the call just now we agreed to drop `animal_scientific_name` and keep `platform_scientific_name`.

**Comment by iamchrisser** [comment]
After discussing issue 13, we changed our minds and decided to keep `animal_scientific_name` to go along with all of the other `animal_` global attributes.
